title:        Cassandrom
tagline:      Cassandra object modeling tool for node.js
baseurl:      ""
paginate:     1

author:
  name:       Kirils Mensikovs
  url:        https://github.com/kiril-me/cassandrom

theme: jekyll-theme-cayman